services:

  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

  frigate:
    container_name: frigate
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`nvr.gw.lo`)"
      - "traefik.http.routers.frigate.entrypoints=web"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"
    privileged: true # this may not be necessary for all setups
    restart: always
    image: ghcr.io/blakeblackshear/frigate:0.14.0
    #image: ghcr.io/blakeblackshear/frigate:dev-8e31244@sha256:01774efc23e3d54c6f36f244e408fa70ef4ee29213ea493cfdd9659766e94e8c
    #image: ghcr.io/blakeblackshear/frigate:dev-8e31244
    shm_size: "64mb" # update for your cameras based on calculation above
   #  devices:
      # - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-starte
      # - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/frigate:/config
      - /video:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    # ports:
      #- "8971:8971"
      #- "5000:5000" # Internal unauthenticated access. Expose carefully.
      #- "8554:8554" # RTSP feeds
      #- "8555:8555/tcp" # WebRTC over tcp
      #- "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "NotSecret!"

